[font]
size = 12.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.65
blur = true

[window.padding]
x = 18
y = 16

[window.dimensions]
columns = 85
lines = 40

[general]
live_config_reload = true
