# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
print_info() {
    prin "\n"
    prin "\n"
    prin "\n"
    prin "┌──────────────────────────────────────┐"
    info " ​ ​ OS" distro
    info " ​ ​ Host" model
    info " ​ ​ Kernel" kernel
    info " ​ ​ Packages" packages
    info " ​ ​ Uptime" uptime
    info " ​ ​ CPU" cpu
    info " ​ ​ GPU" gpu
    info " ​ ​ Memory" memory
    prin "└──────────────────────────────────────┘"

    prin "\n"
    prin "\n \n \n \n \n \n \n \n \n ${cl0}⬤ ${cl7}⬤ ${cl6}⬤ ${cl5}⬤ ${cl4}⬤ ${cl3}⬤ ${cl2}⬤ ${cl1}⬤"
}

# Memory


# Show memory pecentage in output.
#
# Default: 'off'
# Values:  'on', 'off'
# Flag:    --memory_percent
#
# Example:
# on:   '1801MiB / 7881MiB (22%)'
# off:  '1801MiB / 7881MiB'
memory_percent="on"

# Change memory output unit.
#
# Default: 'mib'
# Values:  'kib', 'mib', 'gib'
# Flag:    --memory_unit
#
# Example:
# kib  '1020928KiB / 7117824KiB'
# mib  '1042MiB / 6951MiB'
# gib: ' 0.98GiB / 6.79GiB'
memory_unit="mib"


# Misc Options

# Stdout mode
# Turn off all colors and disables image backend (ASCII/Image).
# Useful for piping into another command.
# Default: 'off'
# Values: 'on', 'off'
stdout="off"
